apiVersion: v1
kind: Service
metadata:
  name: test-quagga
spec:
  selector:
    app: quagga
  ports:
    - name: zebra
      protocol: TCP
      port: 2601
    - name: bgpd
      protocol: TCP
      port: 2605
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-quagga
spec:
 replicas: 1
 strategy:
   type: Recreate
  template:
    metadata:
      labels:
        app: quagga
    spec:
      hostNetwork: true
      containers:
      - name: quagga
        image: quagga:v0.1
        securityContext:
          privileged: true
        ports:
        - containerPort: 2601
        - containerPort: 2605